### ISSUE TITLE
Login problems in older versions

### ISSUE THREAD

**Issue by Fairbrook** [nizewn/moodle-scrape#2]
I know is probably a version error, or just the specific site I'm trying to scrape. I can make the changes in my own fork but is the maintainer of the repo interested in reviewing a pull request?

**Comment by dotnize** [comment]
Yes, but I'll have to check if it still works with the site I'm scraping (v3.8).
If it doesn't, then we could probably add an optional parameter in `.login()` or something that uses your changes to maintain compatibility with both versions.

**Comment by Fairbrook** [comment]
Sounds grate, if its not a problem, could you provide the link to your moodle site? Maybe we can make something that works for both

**Comment by dotnize** [comment]
Thanks, but I'll just test it myself when you submit your PR since I'm scraping my university site and registrations there are disabled :)

**Comment by Fairbrook** [comment]
Submited #3 please let me know if something doesnt work
